name: tickets
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
#  tiket_widget: ^0.0.1
  flutter_countdown_timer: ^4.1.0
  shared_preferences: ^2.0.15
  firebase_core: ^2.4.1
  http: ^0.13.5
  file_picker: ^5.2.5
  dio: ^5.0.1
  flutter_otp_text_field: ^1.1.1
  fluttertoast: ^8.1.1
  path_provider: ^2.0.13
  image_picker: ^0.8.6+3
  getwidget: ^3.0.1
  dotted_border: ^2.0.0+2
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  logger: ^1.1.0
  pinput: ^2.2.16
  #  git:
    # url: https://github.com/Tkko/Flutter_Pinput
  #   ref: dev 
  dropdown_search: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.10.0"
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  build_runner: ^2.3.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "Assets/image/Onepluslogo.png"
  min_sdk_android: 21



flutter:
  uses-material-design: true
  assets:
#     - assets/image/ticket_no.png
     - assets/image/OnePlus_logo.png
     - assets/image/ticket_no.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
#  fonts:
#     - family: Roboto Font Family
#       fonts:
#         - asset: fonts/Roboto-Regular.ttf
#           weight: 400
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Regular.ttf
          weight: 900

  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
